version: '3.8'

services:
  web_proxy:
    image: nginx:1.17-alpine
    container_name: web_proxy
    restart: ${RESTART_POLICY}
    ports:
      - ${NGINX_PUBLIC_PORT}:80
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ${STATIC_DATA_VOLUME}:/static-data
      - ${GSKY_DATA_VOLUME}:/gskydata
      - ${HW_NEXT_STATIC_VOLUME}:/hw/static
      - ${CMS_MAPVIEWER_NEXT_STATIC_VOLUME}:/cms-mapviewer/static
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true