version: '3.8'

services:
  web_proxy:
    image: nginx:1.17-alpine
    container_name: web_proxy
    restart: ${RESTART_POLICY}
    ports:
      - ${NGINX_PUBLIC_PORT}:80
    volumes:
      - ./nginx/default.conf/:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true